### ISSUE TITLE
Format contact information

### ISSUE THREAD

**Issue by scottrohrig** [scottrohrig/got-hops#19]
## Issue

- phone numbers displaying as single set of numbers without separators (555) 555-555 etc.
  - Use string formatting and `'...'.slice(start, stop)` to format them (may require validation).
- web urls have the protocols `http...w.`, but should display simply the domain name
  - Use regex to replace any protocol substrings with empty strings ''
  ```js
  let urlStr = 'https://www.example.com'
  // either use URL constructor && regex
  let urlDomain = new URL( urlStr ).host.replace(/^www./, '')
  
  // or regex only
  let regex = /.*www.|.*\/\//
  urlStr.replace(regex, '')
  ```

**Comment by alex-d-marten** [comment]
When clicking the link to the website add target=_blank to open the site in a new tab
