### ISSUE TITLE
Determine alternative css framework

### ISSUE THREAD

**Issue by scottrohrig** [scottrohrig/got-hops#2]
## Description

- Find an alternative css framework to use instead of Bootstrap
- List the benefits of at least 2 other frameworks
- Note some basic syntax

**Comment by scottrohrig** [comment]
@RogueStorm7 @alex-d-marten 
- I created a develop branch and added permission to require approval before merging.
- I created the basic project structure in develop for us, with empty files etc. 
- We need to review the pull request and merge it into main.
- Please pull and checkout develop. Then create your own feature/branch and checkout to it before making edits to the code.

**Comment by RogueStorm7** [comment]
Will do after tutoring call at 4

**Comment by scottrohrig** [comment]
We decided we will be using tailwind.
