### ISSUE TITLE
Pseudo coding the script.js file 

### ISSUE THREAD

**Issue by scottrohrig** [scottrohrig/got-hops#6]
## Description

- outline the basic functionality of the script file.
-

**Comment by alex-d-marten** [comment]
- Need to determine how many breweries we want to display
- Loop through the brewery array to create html elements
- When looping, access array info needed and store as a temp variable in the loop
- Use this info to create the html elements one at a time for each loop
- When the star or "add to favorites" icon is clicked, store key information to localStorage needed to render content on the Favorite.html page (maybe display a message indicated the favorite was added?)
- Add an event handler for when the "favorites" link is clicked
- Create a separate JavaScript file for the Favorite.html to render content on the page

**Comment by alex-d-marten** [comment]
```js
var retrieveStoredContent = function() {
    // TODO:
        // [] add favoriteBreweries = localStorage.getItem('localStorage Key Name');
        // [] make a call to this whenever a save button is clicked
}

var renderContent = function(breweries) {

    // TODO:
        // [] add for(var i=0; i < breweries.length; i++) loop 
        // [] declare variables for brewery name, brewery type, brewery website, brewery address and brewery phone
            // address will need to be a combination of the brewery object properties
        // [] add unique id to each brewery card
        // [] add the "Star" to each card and provide a matching unique id to this
            // this will help when saving content
        // [] add necessary classes to the html elements
        // [] append variables to correct containers
        // [] add call to this at the end of callBreweryAPI() and pass the data into it
};

var submitBtnClicked = function() {
    ...
    // TODO:
        // [] add cityInputEl[0].value = ""; to bottom of submitBtnClicked() to clear input content
}

var saveBtnClicked = function() {
    // TODO:
        // [] replace the spaces with a _ or a %20
        // [] push the saved brewery name to the favorites array
}

var saveFavorites = function() {
    // TODO:
        // add localStorage.setItem('keyname', favoritesArray);
}
```

**Comment by scottrohrig** [comment]
I realized that we should store the brewery object in the favorites and just make the favorite cards from the data in the favorites instead of making a new fetch request for each favorite. 

We just need to handle storing the brewery data with the correct formatting when the favorites button is toggled. 

Alex, you were right that we should have 2 arrays. But the results array doesn't need to be stored in local storage. 

```js
// On search 👉🔘
// Fetch brewery data
// Parse each brewery obj
// Make result cards
// add brewery obj to brewery array
// Assign each card meta data based on index in results array

card.setAttribute('data-id', arrayIndex)

// On fav star pressed 👉🔘
// Check if obj is in fav array

// If it is, remove it

// else, add it
// Retrieve card brewery obj from results array
//     using data-id 
//     Push obj into fav array

// Save fav array to local storage

```
